version: '3'
services:
  #Aplicacao web do sistema de estoque
  app_estoque:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./gestao_estoque:/app
    depends_on:
      - db_estoque  
  #Banco da Aplicacao em "producao" // eu sei que so de mentirinha mas sou fa do postigres
  db_estoque:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: db_estoque
      POSTGRES_HOST_AUTH_METHOD: trust
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # para verificar as credenciais de acesso ao banco
    # psql -h db_estoque -U db_usuario -d db_estoque

