version: '3'

services:
  #Aplicacao web do sistema de estoque
  ruby:
    build:
      context: ./gestao_estoque
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gestao_estoque:/app
    depends_on:
      - postgres  
    networks:
      - my_network

  #Banco da Aplicacao em "producao"
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      #host do banco
      POSTGRES_DB: db_estoque
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
      # sudo rm -rf data
    ports:
      - 5432:5432
    networks:
      - my_network

  #Interpretador python que altera o banco.
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/python
    depends_on:
      - postgres
    networks:
      - my_network
      
networks:
  my_network:

