version: '3'
services:
  #Aplicacao web do sistema de estoque
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gestao_estoque:/app
    depends_on:
      - postgres  
    networks:
      - my_network
  #Banco da Aplicacao em "producao" // eu sei que so de mentirinha mas sou fa do postigres
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      #host do banco
      POSTGRES_DB: db_estoque
      POSTGRES_HOST_AUTH_METHOD: trust
    # volumes:
    #   - ./data:/usr/local/bin/pg_config
    ports:
      - 5432:5432
    networks:
      - my_network
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/python
    depends_on:
      - postgres
    networks:
      - my_network
networks:
  my_network:

